### ISSUE TITLE
Such 3.6.0, very not on PyPI

### ISSUE THREAD

**Issue by hroncok** [Olivia5k/doge#65]
Hey doge, I've found out 3.6.0 is tagged but missing from PyPI.

![a confusing gif](https://media.tenor.com/images/490da7b3c1773f6712372cd9c020f5d3/tenor.gif)

**Comment by BachoSeven** [comment]
@harkabeeparolus as a few PRs have been merged, it'd be a good time to tag a release and push it on PypI

**Comment by harkabeeparolus** [comment]
> @harkabeeparolus as a few PRs have been merged, it'd be a good time to tag a release and push it on PypI

That's the goal! 😄 I'll see what I can do to get it into good shape.

**Comment by harkabeeparolus** [comment]
> @harkabeeparolus as a few PRs have been merged, it'd be a good time to tag a release and push it on PypI

Version 3.7.0 is now on PyPI. 😊
