### ISSUE TITLE
repology badge in readme

### ISSUE THREAD

**Issue by quantenzitrone** [Olivia5k/doge#75]
[![Packaging status](https://repology.org/badge/vertical-allrepos/doge.svg)](https://repology.org/project/doge/versions)

```md
[![Packaging status](https://repology.org/badge/vertical-allrepos/doge.svg)](https://repology.org/project/doge/versions)
```

**Comment by harkabeeparolus** [comment]
Hi, sorry for responding so slowly! I didn't see this post before. 😳

I'm not entirely sure what this information means. Could you please tell me what you would like to happen? 😊

**Comment by quantenzitrone** [comment]
add the badge to the readme, so everyone can easily see where it is packaged and how up to date the package is there
it provides alternative installation methods to pip

**Comment by harkabeeparolus** [comment]
I think the badge is way too large as is... It would be longer than the entire readme file. 😉 But I think it's a good idea to link to Repology.

I made a draft with some shields and badges, please take a look at <https://github.com/harkabeeparolus/doge> and tell me what you think. 😊

**Comment by quantenzitrone** [comment]
looks good :+1: 
maybe also add a note to the install section, that doge can also be found in some distros repositories

**Comment by quantenzitrone** [comment]
there is also a shorter badge that excludes all the end-of-life repositories

[![Packaging status](https://repology.org/badge/vertical-allrepos/doge.svg?exclude_unsupported=1)](https://repology.org/project/doge/versions)

```md
[![Packaging status](https://repology.org/badge/vertical-allrepos/doge.svg?exclude_unsupported=1)](https://repology.org/project/doge/versions)
```
